library(plm)
data <- read.csv2("C:/Users/Brahim/Desktop/gravity.csv", stringsAsFactors=TRUE)
pdata <- pdata.frame(data,index = c("pair","year"))
pool <- plm(log(trade) ~ log(gdp_a) + log(gdp_b) + log(distance), data = pdata, model = "pooling")
summary(pool)
within <- plm(log(trade) ~ log(gdp_a) + log(gdp_b) + log(distance), data = pdata, model = "within")
summary(within)
between <- plm(log(trade) ~ log(gdp_a) + log(gdp_b) + log(distance), data=pdata,model="between")
summary(between)
random <- plm(log(trade) ~ log(gdp_a) + log(gdp_b) + log(distance), data = pdata, model = "random")
summary(random)
phtest(random, within)
pFtest(within, pool)
plmtest(pool)
